### PR TITLE
translate automatic

### PR DESCRIPTION
**Pull request by tyboro2002**
I created a simple python program that translate a file line by line with the google_translator
to use it 
```
pip install deep_translator

```
and then just run the program and use the shortned name for the lang

### CODE REVIEW

**Comment by krishyadav007** [comment]
Does this use GitHub action??

**Comment by tyboro2002** [comment]
What do you mean with github action

**Comment by krishyadav007** [comment]
https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

**Comment by tyboro2002** [comment]
no it dosnt include that

**Comment by krishyadav007** [comment]
Ok amazing then

**Pull request merged**
